### ISSUE TITLE
go mod  报错问题 go build 报错 

### ISSUE THREAD

**Issue by sunshinean** [mojocn/base64Captcha#104]
vendor/github.com/mojocn/base64Captcha/fonts_embedded.go:4:2: cannot find package "." in:
        /app/vendor/embed

**Comment by mojocn** [comment]
有可能go你的版本 太低 不支持  embed

**Comment by sunshinean** [comment]
1.17版本了

**Comment by mojocn** [comment]
你的项目使用的是 gopath 非 go mod ？

**Comment by sunshinean** [comment]
我的项目就是 go mod
