### ISSUE TITLE
参数导致BUG

### ISSUE THREAD

**Issue by zhuxianglong** [mojocn/base64Captcha#109]
![image](https://user-images.githubusercontent.com/17524804/215688957-85002aea-562a-4515-8654-c05caaf3d7c7.png)
![image](https://user-images.githubusercontent.com/17524804/215688990-eb45e7fc-8ffa-43ee-8b55-a63d7750a79c.png)
captcha.go,高度参数会导致异常，直接painc了并没有返回error，我觉得应该验证下或者返回error

**Comment by anyfig** [comment]
同样的问题，你怎么解决的？

**Comment by zuiwuchang** [comment]
這是 rand.Intn 因爲參數 <=0 而執行了 painc。我搜索了下 base64Captcha 中大量代碼都調用了 rand.Intn。所以會有很多不確定的情況導致 rand.Intn 執行 painc。(例如在創建 DriverString 是 Height 設置<16。或者在創建 DriverDigit 時 Height 設置 <7，...) 每種不同的 Driver 要求的屬性合法值都不一樣但創建 Driver 並沒有驗證有效屬性並爲錯誤屬性返回 error。這對正確調用 base64Captcha 造成了很大的負擔

鑑於 rand.Intn 被調用太頻繁，要去爲每個 Driver 驗證參數應該會相當繁瑣。本喵的建議是在源碼中寫一個 randIntn 函數

```
func randIntn(n int) int{
   if n <= 0 {
      return 0
   }
   return rand.Intn(n)
}
``` 

然後將源碼中的所有 `rand.Intn(` 替換爲 `randIntn(` 這樣當 Driver 某些參數不當時就不會引發 painc

當官方修復這一bug前恐怕只能自己 fork 一份來執行上述代碼替換。或者當你在創建任何 driver 前先自行確保屬性值是合法的
