### ISSUE TITLE
Verify方法的clear参数，

### ISSUE THREAD

**Issue by ilaziness** [mojocn/base64Captcha#117]
clear参数是true的时候，不是应该验证通过之后才失效吗？实际使用中，像百度的图形验证码，第一次看错了输入错误，第二次再输入还是有效的。

**Comment by zuiwuchang** [comment]
在用戶輸入時一般都是使用 ajax 調用驗證並將 clear 設置爲 false。只有在用戶真的提交動作時才以 clear true 驗證。

例如在登入時要輸入驗證碼。一般在點擊登入按鈕前，你在驗證碼輸入框裏面輸入時，前端就會使用 ajax 驗證你輸入的驗證碼是否正確並顯示一個勾或叉。此時 ajax 請求的驗證 clear 設置爲 false 所以可以重複請求驗證。只有當用戶點擊登入時，一般會將登入信息和驗證碼一起發送給後端，後端此時使用 clear 爲 true 來驗證驗證碼。所以登入失敗後無論驗證碼是否輸入正確通常都會刷新一個新的驗證碼給你輸入
