### ISSUE TITLE
don't clear the store when verify is right

### ISSUE THREAD

**Issue by tornodo** [mojocn/base64Captcha#12]
前端会验证这个验证码是否正确，然后提交给后台，后台还会再次验证（后台跟验证码服务是分开的两个服务），这个时候已经删掉了。我添加了一个配置项来控制是否需要在验证成功后就删除掉。
```
@@ -39,6 +39,8 @@ var (
  globalStore = NewMemoryStore(GCLimitNumber, Expiration) 
  //thisPackageDirPath current package path. 
  thisPackageDirPath = "" 
  // ClearWhenVerifyRight default don't clear when verify is right 
  ClearWhenVerifyRight = false 
) 
 
// SetCustomStore sets custom storage for captchas, replacing the default 
@@ -106,7 +108,7 @@ func VerifyCaptcha(identifier, verifyValue string) bool {
  } 
  result := strings.ToLower(storeValue) == strings.ToLower(verifyValue) 
  if result { 
    globalStore.Get(identifier, true) 
    globalStore.Get(identifier, ClearWhenVerifyRight) 
  } 
  return result 
} 
```

**Comment by gopherGod** [comment]
#### 谢谢你的建议
[`func VerifyCaptchaAndIsClear(identifier, verifyValue string,isClear bool) bool`](https://github.com/mojocn/base64Captcha/commit/7d0b78ad1685f79a0fea381c107d77ec1f812500)

**Comment by JJJJJJJerk** [comment]
#### 谢谢你的建议
[`func VerifyCaptchaAndIsClear(identifier, verifyValue string,isClear bool) bool`](https://github.com/mojocn/base64Captcha/commit/7d0b78ad1685f79a0fea381c107d77ec1f812500)
