### ISSUE TITLE
为什么算数每次都是56-40

### ISSUE THREAD

**Issue by 107295472** [mojocn/base64Captcha#15]
第一次打开页面验证码都是56-40

**Comment by mojocn** [comment]
把你的代码贴出来看一下吧  或者参照demo

**Comment by 107295472** [comment]
`func CaptchaWriterHandler(c *gin.Context) {
	//config struct for Character
	var config = base64Captcha.ConfigCharacter{
		Height: 60,
		Width:  205,
		//const CaptchaModeNumber:数字,CaptchaModeAlphabet:字母,CaptchaModeArithmetic:算术,CaptchaModeNumberAlphabet:数字字母混合.
		Mode:               base64Captcha.CaptchaModeArithmetic,
		ComplexOfNoiseText: base64Captcha.CaptchaComplexLower,
		ComplexOfNoiseDot:  base64Captcha.CaptchaComplexLower,
		IsUseSimpleFont:    true,
		IsShowHollowLine:   true,
		IsShowNoiseDot:     false,
		IsShowNoiseText:    false,
		IsShowSlimeLine:    false,
		IsShowSineLine:     false,
		CaptchaLen:         6,
	}
	//create a captchaInterface instance.
	//GenerateCaptcha first parameter is empty string,so the package will generate a random uuid for you.
	_, captchaInterfaceIntance := base64Captcha.GenerateCaptcha("vcode", config)

	//write the httpResponseCookie with idKey.
	//https://golang.org/pkg/net/http/#SetCookie
	//c.SetCookie("vcode", idkey, 300, "/", "", true, false)
	//fmt.Println(idkey)
	//write the content of captcha interface instance to httpResponseWriter.
	_, _ = captchaInterfaceIntance.WriteTo(c.Writer)
	//fmt.Println(n)
}`

**Comment by mojocn** [comment]
```
		Height: 60,
		Width:  205,
		//const CaptchaModeNumber:数字,CaptchaModeAlphabet:字母,CaptchaModeArithmetic:算术,CaptchaModeNumberAlphabet:数字字母混合.
		Mode:               base64Captcha.CaptchaModeArithmetic,
		ComplexOfNoiseText: base64Captcha.CaptchaComplexLower,
		ComplexOfNoiseDot:  base64Captcha.CaptchaComplexLower,
		IsUseSimpleFont:    true,
		IsShowHollowLine:   true,
		IsShowNoiseDot:     false,
		IsShowNoiseText:    false,
		IsShowSlimeLine:    false,
		IsShowSineLine:     false,
		CaptchaLen:         6,
	}
	//create a captchaInterface instance.
	//GenerateCaptcha first parameter is empty string,so the package will generate a random uuid for you.
	_, captchaInterfaceIntance := base64Captcha.GenerateCaptcha("vcode", config)
```
创建captchaInterfaceIntance的代码放在init方法里面,放在init方法里面 应用启动是创建对象就一次,每个request访问的captchaInterfaceIntance都是一个
你上面代码 每一次请求都会创建captchaInterfaceIntance 对象

**Comment by 107295472** [comment]
captchaInterfaceIntance  这个实例没有改变验证码的方法啊

**Comment by Ryanpulu** [comment]
应当在 程序入口 main 方法里，设置 rand.Seed() 随机散列
