### ISSUE TITLE
调用一次才生成一次啊

### ISSUE THREAD

**Issue by 107295472** [mojocn/base64Captcha#16]
_, CaptchaIntance = base64Captcha.GenerateCaptcha("vcode", config)

实例没有刷新验证码的方法啊

**Comment by mojocn** [comment]
之前说说错了,
GenerateCaptcha 第一个参数 是空字符串, 会生成一个随机的验证码id,对应一个图片

GenerateCaptcha 第一个参数要么是浏览器随机产生的 要么空字符串 服务器给你生成
![image](https://user-images.githubusercontent.com/34467684/42015253-2a511b26-7ad9-11e8-9f58-1e48ed5dac52.png)

**Comment by 107295472** [comment]
谢谢
