### ISSUE TITLE
The same identifier can be check for many time until success

### ISSUE THREAD

**Issue by xuantegit** [mojocn/base64Captcha#17]
According to my ideas, one identifier just can be checked/verified once, even the check result is failure. Else someone can initiate a violent collision for one identifier.

**Comment by mojocn** [comment]
GenerateCaptcha first parameter is empty string,so the package will generate a random uuid for you.
`idKeyA,capA := base64Captcha.GenerateCaptcha("",configA)`
call `GenerateCaptcha("",configA)` as many times you like
