### ISSUE TITLE
你好，语音的杂音很大，这个是那块问题

### ISSUE THREAD

**Issue by xhochipe** [mojocn/base64Captcha#20]
首先感觉博主这么好的库，发现语音有杂音，不知道这么回事

**Comment by JJJJJJJerk** [comment]
![image](https://user-images.githubusercontent.com/8449878/45544240-59972080-b849-11e8-8c21-42cf49e80f1e.png)
到这去调整背景噪音 或者直接关掉噪音

**Comment by JJJJJJJerk** [comment]
我下周一 增加一个关闭背景噪音的选项. 如果有兴趣你可以自己打断点 自己看一下
