### ISSUE TITLE
memoryStore data race

### ISSUE THREAD

**Issue by zalecn** [mojocn/base64Captcha#22]
vendor/github.com/mojocn/base64Captcha/store.go:76
`s.Lock()
	s.digitsById[id] = value
	s.idByTime.PushBack(idByTimeValue{time.Now(), id})
	s.numStored++
	s.Unlock()
	if s.numStored > s.collectNum {
		go s.collect()
	}
`
s.numStored read  must in lock scope

**Comment by mojocn** [comment]
thanks for your reporting.
`s.idByTime.PushBack(idByTimeValue{time.Now(), id})` PushBack inserts a new element e with value v at the back of list.   PushBack` is a set actions.
> // Lock locks rw for writing.
>// If the lock is already locked for reading or writing,
so `s.Lock` will lock reading and writing
