### ISSUE TITLE
efficiency problem

### ISSUE THREAD

**Issue by wangzedong** [mojocn/base64Captcha#24]
https://github.com/mojocn/base64Captcha/blob/master/captcha.go#L108
func VerifyCaptchaAndIsClear(identifier, verifyValue string,isClear bool) bool {
	if verifyValue == "" {
		return false
	}
	storeValue := globalStore.Get(identifier, false)
	if storeValue == "" {
		return false
	}
	result := strings.ToLower(storeValue) == strings.ToLower(verifyValue)
	if result {
		globalStore.Get(identifier, isClear)
	}
	return result
}

this function has two destination,one is verity and another is clear the value in the store

why globalStore.Get(identifier, false) called twice，can't run it in one operation?

**Comment by mojocn** [comment]
thanks for your awesome report
