### ISSUE TITLE
图片验证码建议加入亮色、暗色模式

### ISSUE THREAD

**Issue by heyingjie** [mojocn/base64Captcha#29]
建议加入亮色、暗色模式，不然生成的验证码图片在颜色较深的页面下显示效果不是很好。

![QQ截图20190516104606](https://user-images.githubusercontent.com/11901953/57822841-ec68d000-77c7-11e9-9fe5-e035ba212f7d.png)

**Comment by mojocn** [comment]
under development 
   https://github.com/mojocn/base64Captcha/commit/843dd91e7df0bce24fb0b5b1e111fb2eaa926ef8

**Comment by mojocn** [comment]
http://home.mojotv.cn:8777/  增加bg color
