### ISSUE TITLE
提点小意见

### ISSUE THREAD

**Issue by Think-Jumper** [mojocn/base64Captcha#3]
RT，东西是好东西，但是使用各种不方便，环境搭配各种需要用户下载下来自己做处理，完全可以做得更好，一键式下载后直接就可以应用运行。只是提点小建议，不要见怪。

RT，the proejct is good, but not conveniently enough.It need to deal with something when users download the lib. It's absolutly can be done much better than this such as like that:one key finish for using. Just a little tiny advice.Don't be mind.

**Comment by mojocn** [comment]
写这段代码本来是做一个第三方golang包,同时提供验证码配置参数的调试面板. 让大家可以快速的把验证码整合到自己的代码golang 项目里面.
