### ISSUE TITLE
增加delete 调用

### ISSUE THREAD

**Issue by alpha-baby** [mojocn/base64Captcha#30]
`type Store interface`

这个接口目前只有，
```
	Set(id string, value string)
	Get(id string, clear bool) string
```

这两个方法，是不是可以考虑增加一个，`Delete((id string)`方法，

**Comment by JJJJJJJerk** [comment]
`	Get(id string, clear bool) string`
这个方法旧满足delete 如果你需要可以自己实现delete方法
