### ISSUE TITLE
关于验证码的验证方式

### ISSUE THREAD

**Issue by iveryo** [mojocn/base64Captcha#35]
目前使用，采用的idkey+输入值的方式验证
但考虑到多服务并行工作时，集群的进行工作，是否有考虑过？

**Comment by JJJJJJJerk** [comment]
自定义store 使用redis   https://github.com/mojocn/base64Captcha/tree/master/_examples_redis

**Comment by iveryo** [comment]
哦，谢谢，了解一下

**Comment by iveryo** [comment]
`func (s *customizeRdsStore) Set(id string, value string) {
	err := s.redisClient.Set(id, value, time.Minute*10).Err()
	if err != nil {
		log.Println(err)
	}
}`
感觉封装上有疑问
自定义的Store函数Set或Get内出现redis访问错误时，也只能够打一下日志
不能将错误的处理结果返回到GenerateCaptcha或VerifyCaptcha是吗？
但业务端是最需要了解这次事务是否成功的，而不只是打印日志

**Comment by JJJJJJJerk** [comment]
建议你把 log.Println(err) 改写成panic(err), 


 一般引起reids get/set 错误多办是redis挂了,  redis配置连接失败直接log.Fatal.

**Comment by iveryo** [comment]
恩，只能这样了
不过对于事务执行失败时，最好能反应错误信息，而return err的方式我觉得更可取了
THK

**Comment by JJJJJJJerk** [comment]
这个库代码不多   你有兴趣可以自己实现!!!

**Comment by GerryLon** [comment]
> 自定义store 使用redis https://github.com/mojocn/base64Captcha/tree/master/_examples_redis

此链接已经失效了.

**Comment by mojocn** [comment]
> > 自定义store 使用redis https://github.com/mojocn/base64Captcha/tree/master/_examples_redis
> 
> 此链接已经失效了.

我重构了一下导致链接失效了

https://github.com/mojocn/base64Captcha/blob/v1.2.2/_examples_redis/main.go.md
