### ISSUE TITLE
验证建议

### ISSUE THREAD

**Issue by jianglihua** [mojocn/base64Captcha#36]
验证码第一次错误，就会把里面的值给清空，导致后面即使输入正确，仍然是验证失败。看代码，是因为验证就清空。建议：提供一个接口，可以根据id，主动清空

**Comment by mojocn** [comment]
`https://github.com/mojocn/base64Captcha/blob/master/captcha.go`    line 110  `VerifyCaptchaAndIsClear`  就有这个方法

**Comment by jianglihua** [comment]
是的，我知道有这个接口，但是这个接口不纯粹。做了两件事情。
