### ISSUE TITLE
验证码图片有概率显示不全

### ISSUE THREAD

**Issue by xdxiaodong** [mojocn/base64Captcha#37]
验证码图片有概率显示不全  
![captcha](https://user-images.githubusercontent.com/7643447/67617386-304f0f00-f815-11e9-94e9-1157e184dbdd.png)

**Comment by mojocn** [comment]
你这个应该是width height 没有选择好

你先到这个页面 https://captcha.mojotv.cn/  把配置参数调试好, 在把配置参数写到代码中.

**Comment by du5** [comment]
您好 这个页面 两个 CheckBox 同名 
![image](https://user-images.githubusercontent.com/54979375/68994159-ccbb7d00-08ba-11ea-8e63-d20fc77daf89.png)
