### ISSUE TITLE
验证码功能很齐全, 很好很强大, 但是想提一个小小的请求

### ISSUE THREAD

**Issue by medivh-jay** [mojocn/base64Captcha#40]
- 就是关于 globalStore ，能否提供一个对  Captcha 的封装, 然后可以对于不同的验证码实例使用不同的存储对象，而不是全局统一实例操作

**Comment by mojocn** [comment]
看这个例子 https://github.com/mojocn/base64Captcha/blob/master/_examples_redis/main.go.md      可以implement `store interface`

**Comment by medivh-jay** [comment]
这个是实现自己的存储器嘛，我的意思是那种，比如
```go
redis1 := NewCustomRedisStore(1)
redis2 := NewCustomRedisStore(10)

captcha1 := base64Captcha.New()
captcha1.SetStore(redis1)

captcha2 := base64Captcha.New()
captcha2.SetStore(redis2)

captcha1.GenerateCaptcha(idKey, config) // 数据存到了 redis1
captcha2.GenerateCaptcha(idKey, config) // 数据存到了 redis2
```

大概这个意思，现在的是
```go
base64Captcha.SetCustomStore(store)
base64Captcha.GenerateCaptcha(idkey, config) // 就所以的生成操作共用的一个存储
```

**Comment by mojocn** [comment]
> 这个是实现自己的存储器嘛，我的意思是那种，比如
> 
> ```go
> redis1 := NewCustomRedisStore(1)
> redis2 := NewCustomRedisStore(10)
> 
> captcha1 := base64Captcha.New()
> captcha1.SetStore(redis1)
> 
> captcha2 := base64Captcha.New()
> captcha2.SetStore(redis2)
> 
> captcha1.GenerateCaptcha(idKey, config) // 数据存到了 redis1
> captcha2.GenerateCaptcha(idKey, config) // 数据存到了 redis2
> ```
> 
> 大概这个意思，现在的是
> 
> ```go
> base64Captcha.SetCustomStore(store)
> base64Captcha.GenerateCaptcha(idkey, config) // 就所以的生成操作共用的一个存储
> ```

这个需求要大改,  还是你自己fork一份自己实现吧,  现在的 captcha 这个包里面没有 captcha struct 创建不多个实例

**Comment by medivh-jay** [comment]
好的，非常感谢
