### ISSUE TITLE
文本验证码内容：顺序的词组

### ISSUE THREAD

**Issue by slayercat** [mojocn/base64Captcha#42]
hi，@mojocn 

感谢审查MR #41 

之前提出CaptchaModeUseRunePairs这个模式， 是由于我这边有个特殊的需求，希望验证码的内容在指定的词组中进行随机。（非随机单字，而是词组）

我看到您对这个做了一些修改。应该是我之前的做法会有不妥之处。

请问我能些什么来帮助完成这个工作？

**Comment by mojocn** [comment]
我添加了你作为 协作者,你应该可以直接提交代码
