### ISSUE TITLE
如何区分验证码key过期或错误？

### ISSUE THREAD

**Issue by birdycn** [mojocn/base64Captcha#44]
VerifyCaptcha 只返回bool，无论是验证码失效还是错误，都是返回假，建议增加一个过期与否的识别

**Comment by slayercat** [comment]
有点好奇，有实际的使用场景需要这个功能吗？

**Comment by birdycn** [comment]
> 有点好奇，有实际的使用场景需要这个功能吗？

@slayercat 

有啊，比如用户注册的时候，验证码错误有可能失效，这个时候需要指引或程序自动更新验证码图片啦。

**Comment by slayercat** [comment]
个人看法，欢迎讨论。

从我的角度来看，一般这种情况下，验证码非预期的失效/过期 算是bug。需要程序处理。这种情况下，库存储的验证码是“丢失”的，因此无法去做验证。

另一方面，用户注册的时候不管验证结果如何，均需要更新验证码。知道是“找不到”，还是“不正确”，本身感觉没有什么好处。

欢迎讨论。

**Comment by slayercat** [comment]
因此，如果需要考虑这个的话，其实可能将验证码的内容和图片直接给调用者可能更合适。库本身不存储验证码。

这样同时解决 了#39 中的疑惑和您的问题。

还请@mojocn 拨冗决策。

**Comment by nagaame** [comment]
我想在生成验证码, 响应前保存到session中, 有什么好的办法嘛?

**Comment by slayercat** [comment]
@nagaame 

直接在Session中保存生成的id即可。

若要直接获取数值，可参考：https://github.com/mojocn/base64Captcha/issues/39#issuecomment-558431517

自己实现store存储，可参考https://github.com/mojocn/base64Captcha/issues/7#issuecomment-376826487

**Comment by nagaame** [comment]
@slayercat 好的, 非常感谢ヽ(￣▽￣)و

**Comment by mojocn** [comment]
v2 支持自定义driver
