### ISSUE TITLE
我不知道是我电脑问题还是怎么回事，用demo都无法运行

### ISSUE THREAD

**Issue by yilcool** [mojocn/base64Captcha#47]
Hello, I found that neither demo nor self configuration can run, and the error has been reported all the time
你好，我发现用demo还是自我配置都是不可以运行的，一直报错

2019/12/13 10:30:39 EOF
2019/12/13 10:30:39 http: panic serving [::1]:61416: runtime error: invalid memory address or nil pointer dereference
goroutine 25728 [running]:
net/http.(*conn).serve.func1(0xc000259360)
        D:/use/Go/src/net/http/server.go:1767 +0x140
panic(0x712300, 0xca1940)
        D:/use/Go/src/runtime/panic.go:679 +0x1c0
github.com/mojocn/base64Captcha.(*DriverDigit).GenerateIdQuestionAnswer(0x0, 0xc000265d70, 0xc000092000, 0x4, 0xc0000bd800, 0xc000092030, 0xcae360)
        D:/path/gopath/pkg/mod/github.com/mojocn/base64!captcha@v0.0.0-20191212120622-2843ab3606bd/driver_digit.go:46 +0x45
github.com/mojocn/base64Captcha.(*Captcha).Generate(0xc000265b10, 0x1, 0x1, 0x7e3480, 0xc000032040, 0x8, 0xc0005af9d0)
        D:/path/gopath/pkg/mod/github.com/mojocn/base64!captcha@v0.0.0-20191212120622-2843ab3606bd/captcha.go:42 +0x41
main.generateCaptchaHandler(0x7e90e0, 0xc00015ba40, 0xc0000c1c00)
        D:/mywork/web/kongbu/main.go:52 +0x238
net/http.HandlerFunc.ServeHTTP(0x78f920, 0x7e90e0, 0xc00015ba40, 0xc0000c1c00)
        D:/use/Go/src/net/http/server.go:2007 +0x4b
net/http.(*ServeMux).ServeHTTP(0xcae320, 0x7e90e0, 0xc00015ba40, 0xc0000c1c00)
        D:/use/Go/src/net/http/server.go:2387 +0x1c4
net/http.serverHandler.ServeHTTP(0xc0000520e0, 0x7e90e0, 0xc00015ba40, 0xc0000c1c00)
        D:/use/Go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc000259360, 0x7e9620, 0xc000a5b840)
        D:/use/Go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        D:/use/Go/src/net/http/server.go:2928 +0x38b
exit status 2

**Comment by mojocn** [comment]
generateCaptchaHandler 这个代码拿出来看一下

**Comment by yilcool** [comment]
你好，我就是用demo的代码
// example of HTTP server that uses the captcha package.
package main

import (
	"encoding/json"
	"fmt"
	"github.com/mojocn/base64Captcha"
	"log"
	"net/http"
)

//configJsonBody json request body.
type configJsonBody struct {
	Id            string
	CaptchaType   string
	VerifyValue   string
	DriverAudio   *base64Captcha.DriverAudio
	DriverString  *base64Captcha.DriverString
	DriverChinese *base64Captcha.DriverChinese
	DriverMath    *base64Captcha.DriverMath
	DriverDigit   *base64Captcha.DriverDigit
}

var store = base64Captcha.DefaultMemStore

// base64Captcha create http handler
func generateCaptchaHandler(w http.ResponseWriter, r *http.Request) {
	//parse request parameters
	decoder := json.NewDecoder(r.Body)
	var param configJsonBody
	err := decoder.Decode(&param)
	if err != nil {
		log.Println(err)
	}
	defer r.Body.Close()
	var driver base64Captcha.Driver

	//create base64 encoding captcha
	switch param.CaptchaType {
	case "audio":
		driver = param.DriverAudio
	case "string":
		driver = param.DriverString.ConvertFonts()
	case "math":
		driver = param.DriverMath.ConvertFonts()
	case "chinese":
		driver = param.DriverChinese.ConvertFonts()
	default:
		driver = param.DriverDigit
	}
	c := base64Captcha.NewCaptcha(driver, store)
	id, b64s, err := c.Generate()
	body := map[string]interface{}{"code": 1, "data": b64s, "captchaId": id, "msg": "success"}
	if err != nil {
		body = map[string]interface{}{"code": 0, "msg": err.Error()}
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	json.NewEncoder(w).Encode(body)
}

// base64Captcha verify http handler
func captchaVerifyHandle(w http.ResponseWriter, r *http.Request) {

	//parse request json body
	decoder := json.NewDecoder(r.Body)
	var param configJsonBody
	err := decoder.Decode(&param)
	if err != nil {
		log.Println(err)
	}
	defer r.Body.Close()
	//verify the captcha
	body := map[string]interface{}{"code": 0, "msg": "failed"}
	if store.Verify(param.Id, param.VerifyValue, true) {
		body = map[string]interface{}{"code": 1, "msg": "ok"}
	}

	//set json response
	w.Header().Set("Content-Type", "application/json; charset=utf-8")

	json.NewEncoder(w).Encode(body)
}

//start a net/http server
func main() {
	//serve Vuejs+ElementUI+Axios Web Application
	http.Handle("/", http.FileServer(http.Dir("./static")))

	//api for create captcha
	http.HandleFunc("/api/getCaptcha", generateCaptchaHandler)

	//api for verify captcha
	http.HandleFunc("/api/verifyCaptcha", captchaVerifyHandle)

	fmt.Println("Server is at :8777")
	if err := http.ListenAndServe(":8777", nil); err != nil {
		log.Fatal(err)
	}
}

下面是generateCaptchaHandler也是demo的，然后访问http://localhost:8777/api/getCaptcha
就会不断滚动报错上面的错误提示，我的版本为go version1.13版本

// base64Captcha verify http handler
func captchaVerifyHandle(w http.ResponseWriter, r *http.Request) {

	//parse request json body
	decoder := json.NewDecoder(r.Body)
	var param configJsonBody
	err := decoder.Decode(&param)
	if err != nil {
		log.Println(err)
	}
	defer r.Body.Close()
	//verify the captcha
	body := map[string]interface{}{"code": 0, "msg": "failed"}
	if store.Verify(param.Id, param.VerifyValue, true) {
		body = map[string]interface{}{"code": 1, "msg": "ok"}
	}

	//set json response
	w.Header().Set("Content-Type", "application/json; charset=utf-8")

	json.NewEncoder(w).Encode(body)
}

**Comment by yilcool** [comment]
我觉得以前那种简书https://www.jianshu.com/p/08319bdd0637 那时候的方法挺好用的啊，为什么要弄到现在使用有点复杂

**Comment by mojocn** [comment]
`go get github.com/mojocn/base64Captcha@v1.20`  使用历史版本go mod

**Comment by mojocn** [comment]
你的问题应该是 d *DriverDigit.Length 这个参数没有 这个必须大于等于1

**Comment by virskor** [comment]
go get github.com/mojocn/base64Captcha@v1.20: no matching versions for query "v1.20"

**Comment by lujscn** [comment]
我也是同样的问题，1.3.1，go版本1.15.1，用的是 https://github.com/mojocn/base64Captcha/blob/master/README.md 上面的“2.3.6 🏃🏃🏃 ‍Full Example”

`go run main.go
Server is at :8777
2020/09/30 00:15:14 EOF
2020/09/30 00:15:14 http: panic serving [::1]:49238: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc00009ea00)
        c:/go/src/net/http/server.go:1801 +0x147
panic(0x11dc5a0, 0x16d3420)
        c:/go/src/runtime/panic.go:975 +0x3e9
github.com/mojocn/base64Captcha.(*DriverDigit).GenerateIdQuestionAnswer(0x0, 0x4, 0xc000552cc0, 0xc0000e4030, 0x16e0080, 0xc0000e4000, 0x1242978)
        C:/Users/luyut/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/driver_digit.go:44 +0x45
github.com/mojocn/base64Captcha.(*Captcha).Generate(0xc000535ad8, 0x1, 0x1, 0x1286420, 0xc000088030, 0x11945bc, 0x16dffc0)
        C:/Users/luyut/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/captcha.go:34 +0x42
main.generateCaptchaHandler(0x128b1c0, 0xc000542000, 0xc00006a100)
        D:/Colin/Projects/go_test/main.go:52 +0x225
net/http.HandlerFunc.ServeHTTP(0x12422b8, 0x128b1c0, 0xc000542000, 0xc00006a100)
        c:/go/src/net/http/server.go:2042 +0x4b
net/http.(*ServeMux).ServeHTTP(0x16dffc0, 0x128b1c0, 0xc000542000, 0xc00006a100)
        c:/go/src/net/http/server.go:2417 +0x1b7
net/http.serverHandler.ServeHTTP(0xc000506000, 0x128b1c0, 0xc000542000, 0xc00006a100)
        c:/go/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00009ea00, 0x128b680, 0xc000520000)
        c:/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2969 +0x36d
2020/09/30 00:15:14 EOF
2020/09/30 00:15:14 http: panic serving [::1]:49239: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:`
