### ISSUE TITLE
go mod 下载的都是1.2.2版本

### ISSUE THREAD

**Issue by freshbird** [mojocn/base64Captcha#50]
请在仓库中区分新旧版本，否则没办法用mod引用。

**Comment by mojocn** [comment]
https://github.com/mojocn/base64Captcha/blob/master/README.md#21--use-history-version

**Comment by sun63270325** [comment]
![1578903604432](https://user-images.githubusercontent.com/44491648/72240990-95e6b680-3620-11ea-89d2-11f30ef8a7d8.jpg)
go mod不能指定最新版本下载

**Comment by mojocn** [comment]
> ![1578903604432](https://user-images.githubusercontent.com/44491648/72240990-95e6b680-3620-11ea-89d2-11f30ef8a7d8.jpg)
> go mod不能指定最新版本下载

我把GOPROXY设置成空白值就可以了

```bash
zhouqing1@zhouqing1-l5 MINGW64 /d/code/awesomeProject
$ GOPROXY=''

zhouqing1@zhouqing1-l5 MINGW64 /d/code/awesomeProject
$ go get github.com/mojocn/base64Captcha@v1.2.2

zhouqing1@zhouqing1-l5 MINGW64 /d/code/awesomeProject
$ go get github.com/mojocn/base64Captcha@v2.0.5
go: finding github.com/mojocn/base64Captcha v2.0.5
go: downloading github.com/mojocn/base64Captcha v0.0.0-20200113034016-a2d78bb88ca6
go: extracting github.com/mojocn/base64Captcha v0.0.0-20200113034016-a2d78bb88ca6
```

**Comment by mojocn** [comment]
不知道,为什么 goproxy 代理会转移 我的url ` https://goproxy.io/github.com/mojocn/base64%21cap
tcha/@v/v2.0.5`  增加%21

**Comment by sun63270325** [comment]
> 不知道,为什么 goproxy 代理会转移 我的url ` https://goproxy.io/github.com/mojocn/base64%21cap tcha/@v/v2.0.5` 增加%21 增加了一个 %21 就是 !

应该是代理下载的包名如果有大写字母，会转换成!加小写，然后通过url编码就有%21了，但实际上没有这个路径

**Comment by mojocn** [comment]
好像 v2.*.*  go get 不识别  我看gin tag都是在没有到2.*.*

我版本号修改从1.3.0 就好了

**Comment by mojocn** [comment]
多谢 这个位大神  终于知道v2的用法
