### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fengjinhai** [mojocn/base64Captcha#51]
2020/01/15 20:02:37 http: panic serving 127.0.0.1:64947: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc00022e000)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1769 +0x139
panic(0x1309aa0, 0x18b27f0)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
github.com/mojocn/base64Captcha.(*DriverDigit).GenerateIdQuestionAnswer(0x0, 0xbf7fddb76af07a38, 0x10f5c6f9d, 0x4, 0xc0001d4e00, 0xc0000cc030, 0x18be7e0)
	/Users/dev/go/src/github.com/mojocn/base64Captcha/driver_digit.go:44 +0x3f
github.com/mojocn/base64Captcha.(*Captcha).Generate(0xc000237be8, 0x13d5c58, 0x18db068, 0x13d1f20, 0xc000084030, 0x0, 0xc000237c80)
	/Users/dev/go/src/github.com/mojocn/base64Captcha/captcha.go:32 +0x3d
main.generateCaptchaHandler(0x13d8080, 0xc0000d60e0, 0xc00029c000)
	/Users/Desktop/test/capture.go:52 +0x230
net/http.HandlerFunc.ServeHTTP(0x137cfd8, 0x13d8080, 0xc0000d60e0, 0xc00029c000)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x18be700, 0x13d8080, 0xc0000d60e0, 0xc00029c000)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00008c9c0, 0x13d8080, 0xc0000d60e0, 0xc00029c000)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00022e000, 0x13d8680, 0xc000058480)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:2884 +0x2f4

**Comment by slayercat** [comment]
hi!

Could you provides a short code snipet to reproduce the problem? 

thankyou.

**Comment by fengjinhai** [comment]
hi, I just copy this code https://github.com/mojocn/base64Captcha#236--full-example  and run.
when I request http://127.0.0.1:8777/api/getCaptcha  the error will report.

![image](https://user-images.githubusercontent.com/3690128/72446103-de070400-37ed-11ea-81f1-7818f4f3b828.png)

**Comment by slayercat** [comment]
Hi,

The code provided is not intend to work with  "GET" method. It requires request body as param.

I suggest you to review [this site](https://captcha.mojotv.cn/)

You may POST these json string to your server:
```
{"ShowLineOptions":[],"CaptchaType":"string","Id":"duV0yNVJNzuSe4FEcqGz","VerifyValue":"","DriverAudio":{"Length":6,"Language":"zh"},"DriverString":{"Height":60,"Width":240,"ShowLineOptions":0,"NoiseCount":0,"Source":"1234567890qwertyuioplkjhgfdsazxcvbnm","Length":8,"Fonts":["wqy-microhei.ttc"],"BgColor":{"R":0,"G":0,"B":0,"A":0}},"DriverMath":{"Height":60,"Width":240,"ShowLineOptions":0,"NoiseCount":0,"Length":6,"Fonts":["wqy-microhei.ttc"],"BgColor":{"R":0,"G":0,"B":0,"A":0}},"DriverChinese":{"Height":60,"Width":320,"ShowLineOptions":0,"NoiseCount":0,"Source":"设想,你在,处理,消费者,的音,频输,出音,频可,能无,论什,么都,没有,任何,输出,或者,它可,能是,单声道,立体声,或是,环绕立,体声的,,不想要,的值","Length":2,"Fonts":["wqy-microhei.ttc"],"BgColor":{"R":125,"G":125,"B":0,"A":118}},"DriverDigit":{"Height":80,"Width":240,"Length":5,"MaxSkew":0.7,"DotCount":80}}
```

**Comment by slayercat** [comment]
I do not think this is a bug. 

At the same time. If you'd like to make a improvement, that would be awesome.

**Comment by fengjinhai** [comment]
Thanks for your mention
