### ISSUE TITLE
More breaking API changes

### ISSUE THREAD

**Issue by Eggbertx** [mojocn/base64Captcha#52]
I've run into errors in my code that uses base64Captcha that worked with previous base64Captcha versions. The errors I'm currently getting are
```Go
default: src/captcha.go:12:17: undefined: base64Captcha.ConfigCharacter
default: src/captcha.go:24:19: undefined: base64Captcha.ConfigCharacter
default: src/captcha.go:75:17: undefined: base64Captcha.VerifyCaptcha
default: src/captcha.go:103:22: undefined: base64Captcha.CaptchaInterface
default: src/captcha.go:104:31: undefined: base64Captcha.GenerateCaptcha
default: src/captcha.go:105:16: undefined: base64Captcha.CaptchaWriteToBase64Encoding
```
I know the code  in question worked previously, but this is the second time that changes to this package's API have broken my code. Is the API so unstable that I can't reliably use it without having to constantly uninstall and reinstall the package just to make sure that I don't have to rewrite code that shouldn't have to be rewritten? The `main.go.md` In the root directory of this repo even uses the previous API.

And I'd use a previous version/tag but for compatibility reasons, I'm not (yet) using Go's module feature, and for the record, the suggested `go get github.com/mojocn/base64Captcha@v1.2.2` command in README.md fails with the error `go: cannot use path@version syntax in GOPATH mode`

**Comment by slayercat** [comment]
The  version v2 made a significant change to API. 

you may use go module to remain the depends of your project to version v1 if you like. 

to solve the `go: cannot use path@version syntax in GOPATH mode` problem. you may try [this](https://stackoverflow.com/questions/54415733/getting-gopath-error-go-cannot-use-pathversion-syntax-in-gopath-mode-in-ubun). In short,  set `export GO111MODULE=on` and retry may help.

However, if you could upgrade golang to v1.13, your question may be solved by the compiler. The [release note](https://golang.org/doc/go1.13#modules) says:
```
GO111MODULE=auto enables module-mode if any go.mod is found, even inside GOPATH. (Prior to Go 1.13, GO111MODULE=auto would never enable module-mode inside GOPATH).
```

on the Opposite,  you may use the `dep` command to set fixed version if you are in the older version of golang. reference [here](https://stackoverflow.com/questions/24855081/how-do-i-import-a-specific-version-of-a-package-using-go-get)

----
A quick but temporary soluction, you could just go to `$GOPATH/mojocn/base64Captcha`, and run:
`git checkout v1.2.2`


Hope this will help, And wish to hear from you soon.

**Comment by slayercat** [comment]
I've never tried. but this may help either:
http://labix.org/gopkg.in

If you've tried this, hope to kindly commit a feedback.

https://gopkg.in/mojocn/base64Captcha.v1

**Comment by Eggbertx** [comment]
Using gopkg.in fixes it
