### ISSUE TITLE
generate函数提示错误

### ISSUE THREAD

**Issue by nagaame** [mojocn/base64Captcha#59]
大概的错误信息

```
invalid argument to Intn
/usr/local/Cellar/go/1.13.8/libexec/src/math/rand/rand.go:169 (0x119266e)
        (*Rand).Intn: panic("invalid argument to Intn")
/usr/local/Cellar/go/1.13.8/libexec/src/math/rand/rand.go:329 (0x119309f)
        Intn: func Intn(n int) int { return globalRand.Intn(n) }
/Users/cpp/golang/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/random_math.go:78 (0x1c8c238)
        randIntRange: return rand.Intn(to-from) + from
/Users/cpp/golang/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/item_digit.go:165 (0x1c8af62)
        (*ItemDigit).drawDigit: y += randIntRange(-r, r)
/Users/cpp/golang/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/driver_digit.go:70 (0x1c84034)
        (*DriverDigit).DrawCaptcha: itemDigit.drawDigit(digitFontData[n], x, y)
/Users/cpp/golang/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/captcha.go:33 (0x1c82aee)
        (*Captcha).Generate: item, err := c.Driver.DrawCaptcha(content)


```

**Comment by heyingjie** [comment]
环境:win64 golang 1.13.9

报同样的问题

Handler crashed with error invalid argument to Intn
2020/03/20 14:24:39.742 [C] [panic.go:679]  c:/go/src/runtime/panic.go:679
2020/03/20 14:24:39.743 [C] [panic.go:679]  c:/go/src/math/rand/rand.go:169
2020/03/20 14:24:39.745 [C] [panic.go:679]  c:/go/src/math/rand/rand.go:329
2020/03/20 14:24:39.748 [C] [panic.go:679]  D:/workspace/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/random_math.go:78
2020/03/20 14:24:39.750 [C] [panic.go:679]  D:/workspace/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/item_digit.go:165
2020/03/20 14:24:39.751 [C] [panic.go:679]  D:/workspace/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/driver_digit.go:70
2020/03/20 14:24:39.753 [C] [panic.go:679]  D:/workspace/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.0/captcha.go:33

代码如下:

var store = base64Captcha.DefaultMemStore
var DefaultDriverDigit = base64Captcha.NewDriverDigit(45, 100, 4, 0.7, 80)
captcha := base64Captcha.NewCaptcha(DefaultDriverDigit, store)
idKeyD, base64stringD, err := captcha.Generate()
if err != nil {
	logs.Error("captcha.Generate失败:" + err.Error())
}

**Comment by heyingjie** [comment]
![image](https://user-images.githubusercontent.com/11901953/77145913-bfaad680-6ac4-11ea-8c1f-dce2e422280e.png)

找到原因了，go module依赖的库中源码没有做这个容错判断，作者可以更新一下仓库

**Comment by nagaame** [comment]
@heyingjie 你可以提交一个pr

**Comment by heyingjie** [comment]
> @heyingjie 你可以提交一个pr

我看你已经修复了，只是没有release

**Comment by nagaame** [comment]
@heyingjie 呃, 其实我也不是作者啦, 我也看到作者是修复了, 没有release

**Comment by heyingjie** [comment]
> @heyingjie 呃, 其实我也不是作者啦, 我也看到作者是修复了, 没有release

没注意，-_-||

**Comment by mojocn** [comment]
https://github.com/mojocn/base64Captcha/tree/v1.3.1
