### ISSUE TITLE
如果多台服务器集群，目前的内存方式不合用

### ISSUE THREAD

**Issue by Leadrive** [mojocn/base64Captcha#6]
项目非常好，谢谢。

提个建议，目前的验证码是保存在内存中，如果多台服务器集群使用时，下次验证时，不一定是之前产生验证码的服务器。

建议修改下生成验证码的函数，可以配置为不保存，返回答案

自己把ID和答案保存到数据库之类，自己验证。

**Comment by Leadrive** [comment]
// VerifyCaptchaWithAnswer 带答案验证
func VerifyCaptchaWithAnswer(answer, verifyValue string) bool {
	if verifyValue == "" {
		return false
	}
	if answer == "" {
		return false
	}
	result := strings.ToLower(answer) == strings.ToLower(verifyValue)

	return result
}

**Comment by Leadrive** [comment]
<pre>
func GenerateCaptcha(idKey string, storeAnswer bool, configuration interface{}) (id string, answer string, captchaInstance CaptchaInterface) {
	if idKey == "" {
		idKey = randomId()
	}
	id = idKey
	var verifyValue string
	switch config := configuration.(type) {
	case ConfigAudio:
		audio := EngineAudioCreate(idKey, config)
		verifyValue = audio.VerifyValue
		captchaInstance = audio

	case ConfigCharacter:
		char := EngineCharCreate(config)
		verifyValue = char.VerifyValue
		captchaInstance = char

	case ConfigDigit:
		dig := EngineDigitsCreate(idKey, config)
		verifyValue = dig.VerifyValue
		captchaInstance = dig

	default:
		log.Fatal("config type not supported", config)
	}

	if storeAnswer {
		globalStore.Set(idKey, verifyValue)
	}

	return idKey, verifyValue, captchaInstance
}
</pre>

**Comment by mojocn** [comment]
非常好的建议 你把代码都写处理啊了 你 fork 一下 提交一个pr 好了
