### ISSUE TITLE
Math 有时候不显示操作符

### ISSUE THREAD

**Issue by razonyang** [mojocn/base64Captcha#63]
```go
base64Captcha.NewDriverMath(80, 220, 0, 0, nil, []string{})
```

![Screenshot_20200308-121934](https://user-images.githubusercontent.com/17720932/76156564-48298e80-6137-11ea-83f5-6dbcdb7a9566.jpg)

**Comment by mojocn** [comment]
应该是字体中缺少缺少操作码符

**Comment by zhan3333** [comment]
`
bs64Captcha.DriverMath{
			//
			Fonts: []string{
				"3Dumb.ttf",
				"ApothecaryFont.ttf",
				"Comismsh.ttf",
				// DeborahFancyDress.ttf 字体的 +- 符号无法显示,故注释掉
				//"DeborahFancyDress.ttf",
				"DENNEthree-dee.ttf",
				"Flim-Flam.ttf",
				"RitaSmith.ttf",
				"actionj.ttf",
				"chromohv.ttf",
				"wqy-microhei.ttc",
			},
`

DeborahFancyDress.ttf 字体无法显示 +- 符号，可以在创建时指定除开该字体，运算符即可正常出现了
