### ISSUE TITLE
完整案例代码运行报空指针，求指教，谢谢

### ISSUE THREAD

**Issue by richfuns** [mojocn/base64Captcha#69]
`2020/04/07 00:19:01 http: panic serving 127.0.0.1:8414: runtime error: invalid memory address or nil pointer dereference
goroutine 48 [running]:
net/http.(*conn).serve.func1(0xc0002501e0)
	D:/Program Files/go/src/net/http/server.go:1767 +0x140
panic(0x704740, 0xc89920)
	D:/Program Files/go/src/runtime/panic.go:679 +0x1c0
github.com/mojocn/base64Captcha.(*DriverDigit).GenerateIdQuestionAnswer(0x0, 0xc000305d70, 0xc0000b2000, 0x4, 0xc00011e000, 0xc0000b2030, 0xc962e0)
	D:/Malaysia/code/Go/fx-go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/driver_digit.go:44 +0x45
github.com/mojocn/base64Captcha.(*Captcha).Generate(0xc000305b10, 0x1, 0x1, 0x7d27a0, 0xc000058030, 0x8, 0xc0003059d0)
	D:/Malaysia/code/Go/fx-go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/captcha.go:34 +0x41
`

完整示例代码运行一直报这个错误，不知道是哪里问题，求指教，谢谢

**Comment by JJJJJJJerk** [comment]
这个日志看不错啦语言,代码paste出来一下

**Comment by richfuns** [comment]
> 这个日志看不错啦语言,代码paste出来一下

https://mojotv.cn/go/refactor-base64-captcha

用的这里的完整实例代码

**Comment by mojocn** [comment]
是这个代码 2.2.6 🏃 完整实例代码 🏃  ?

**Comment by richfuns** [comment]
> 是这个代码 2.2.6 🏃 完整实例代码 🏃 ?

对的，就是这个实例代码

做了以下修改才可以运行
```
default:
//driver = param.DriverDigit
//数字验证码这里要这样初始化才行
driver = base64Captcha.DefaultDriverDigit
```

**Comment by mojocn** [comment]
我那个实力代码要配置 我的 playground 使用, 我在前端做了 默认值, 所以参数绑定的时config参数就全部设置好了.   https://captcha.mojotv.cn/
