### ISSUE TITLE
线上经常会出现验证失败的情况 

### ISSUE THREAD

**Issue by leo0o** [mojocn/base64Captcha#7]
线上经常会出现验证失败的情况 ，填的验证码明明是对的，大家有出现过这种情况吗

**Comment by mojocn** [comment]
请问你使用是自带的验证码store吗?

**Comment by leo0o** [comment]
这是验证部分的逻辑
`if ok := base64Captcha.VerifyCaptcha(idkey, verifyValue); !ok{
		//记录有多少图形验证码验证失败的
		context.Log.Info("[sms][SendMsg]VerifyCaptcha failed, mobile : %s", mobile)
		context.JsonReturn(ctx, false, context.FORBIDDEN, "图文验证码错误", nil)
		return
	}`

**Comment by mojocn** [comment]
你的网站是不是遇到别人机器人,  或者
使用自带的store,验证码有效期就十分钟,10240个验证码没有使用就触发gc的

```go
var (
	// GCLimitNumber The number of captchas created that triggers garbage collection used by default store.
	// 默认图像验证GC清理的上限个数
	GCLimitNumber = 10240
	// Expiration time of captchas used by default store.
	// 内存保存验证码的时限
	Expiration = 10 * time.Minute
	// GlobalStore is a shared storage for captchas, generated by New function.
	// 默认内存储存,实现store.go的中的store interface的协议set和get这两个方法
	GlobalStore = NewMemoryStore(GCLimitNumber, Expiration)
	//thisPackageDirPath current package path.
	thisPackageDirPath = ""
)
```

**Comment by leo0o** [comment]
之前有碰到过被刷，我把失效时间改成1分钟了，现在好像没看到刷了。
但是清理的话，不是只会清理掉已经过期的吗？应该不会清理刚生成的啊。

**Comment by mojocn** [comment]
没有验证成功的验证码会在10240满或者超过10分钟,触发gc, 验证码丢失了
验证成功的验证码会从store你面清除
```
func VerifyCaptcha(identifier, verifyValue string) bool {
	if verifyValue == "" {
		return false
	}
	storeValue := GlobalStore.Get(identifier, false)
	if storeValue == "" {
		return false
	}
	result := strings.ToLower(storeValue) == strings.ToLower(verifyValue)
	if result {
		GlobalStore.Get(identifier, true)
	}
	return result
}
```
![image](https://user-images.githubusercontent.com/34467684/38021870-94fc7bf8-32b0-11e8-9ece-9b2cc69a7102.png)
在base64captcha初始化之前你可以自定义gc数量和时间

**Comment by mojocn** [comment]
如果有机器在刷验证码 会触发gc.导致正常的验证码被清除了,正常的用户验证不了

**Comment by leo0o** [comment]
我看你的 collect() 里面 只会清理掉过过期的啊？

**Comment by leo0o** [comment]
![image](https://user-images.githubusercontent.com/5572910/38022186-735d514c-32b1-11e8-8b5d-aefc25bd65bb.png)

**Comment by leo0o** [comment]
好像知道问题了，生成和验证的请求分别落到不同的机器上面去了

**Comment by mojocn** [comment]
> func SetCustomStore
> func SetCustomStore(s Store)
> SetCustomStore sets custom storage for captchas, replacing the default memory store. This function must be called before generating any captchas.

你可以用redis自定义store 只需要实现store interface 里面set 和 get 方法
