### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by longhaoteng** [mojocn/base64Captcha#71]
谢谢作者，挺好的项目

有些小建议
* 算数验证码加减运算现在默认是100内两位数运算，图形验证码对用户而言本来就是枯燥不友好的设计，两位数加减更是增加了劝退性，希望加减数位能作为参数设置
* 目前字符验证码是区分大小写的，用户体验角度来说建议默认设置为不区分大小写，或者可以使用参数配置化

**Comment by mojocn** [comment]
加减发修改20以内了

**Comment by mojocn** [comment]
https://github.com/mojocn/base64Captcha/commit/21c366b81654a564a8f7cca124023d2acdad125c
