### ISSUE TITLE
invalid memory address or nil pointer dereference goroutine

### ISSUE THREAD

**Issue by huichen2017** [mojocn/base64Captcha#72]
不知道为什么一使用就报错。
runtime error: invalid memory address or nil pointer dereference
goroutine

**Comment by phprao** [comment]
我也是，这个版本的用不了？

**Comment by mojocn** [comment]
你使用demo 代码 config 没有初始化

**Comment by phprao** [comment]
是参数传递问题，再body raw data 输入以下参数试一下 
{"CaptchaType":"digit","Id":"vzFYDhJTKtFYgBQz6Jo4","VerifyValue":"","DriverDigit":{"Height":80,"Width":240,"Length":4,"MaxSkew":0.7,"DotCount":80}}

**Comment by 54huige** [comment]
> 是参数传递问题，再body raw data 输入以下参数试一下
> {"CaptchaType":"digit","Id":"vzFYDhJTKtFYgBQz6Jo4","VerifyValue":"","DriverDigit":{"Height":80,"Width":240,"Length":4,"MaxSkew":0.7,"DotCount":80}}

大佬有较完整的示例吗 最新版的自带demo都能正常跑 代码不报错就是一访问就报错runtime error: invalid memory address or nil pointer dereference

**Comment by vulcangz** [comment]
遇到过，是默认的 "DotCount" 初始值没有设置到、为 0 了。在你 driver 配置参数中加个 "DotCount":80 试试。

**Comment by huichen2017** [comment]
{"CaptchaType":"digit","Id":"vzFYDhJTKtFYgBQz6Jo4","VerifyValue":"","DriverDigit":{"Height":80,"Width":240,"Length":4,"MaxSkew":0.7,"DotCount":80}}
现在可以了，用的上面这个参数，可能重点就是 DotCount":80 这个吧，谢谢大佬们。
