### ISSUE TITLE
使用 sync.Map 有何优势

### ISSUE THREAD

**Issue by dudebing99** [mojocn/base64Captcha#74]
sync.map 能够发挥优势的场景与验证码使用场景似乎没有重叠，请问支持 sync.Map 实现有何优势或者基于哪些考虑？

**Comment by mojocn** [comment]
回想起来没有优势, 只是看起来比较简洁.
现在感觉使用 LRU算法会比较好 https://leetcode-cn.com/problems/lru-cache/

**Comment by dudebing99** [comment]
> 回想起来没有优势, 只是看起来比较简洁.
> 现在感觉使用 LRU算法会比较好 https://leetcode-cn.com/problems/lru-cache/

确实，LRU 比较适合。
