### ISSUE TITLE
The b64s can not use

### ISSUE THREAD

**Issue by Icarus9913** [mojocn/base64Captcha#76]
用代码生成一个DriverString类型的，最后返回的b64s无法正常显示，例如：data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAAA8CAYAAABYfzddAAALs0lEQVR4nOydC5QT1f3Hv8NrF0Xd/RMl8QH5+6a6elqLOjCg06pRLFI3tdbWRyvFBz5ybGOO2tZT6LFojNZQq6hVaeujqAFb8RHsYdoyOLCoVLQgCCVw2k0WAiyPsgsLpGeWm93Zskp0nuZ9zck5+d+4MPzbzvfd334PAqCq8wXBOY47JJGIf2uiOJfg88RyVdEM6G3rJJncMZYDdDjAYjMphAmYwXAwTcHVDh5YMl8EEXN102O0Ao3+wTqzqZi8OdWxdCmAagLEAhgPYDeBzAAkAv8kkYnvsdpShD6uBq5u93mD4aQALAXwTwHEABgI4BsAFAKIAVnmD4Qa7HWXowwRc3TwA4DbyfRWAPwF4E8B6TZ5RABZ5g+GTbPLRDA7a7YBRsBC6upkKYAOA72QSsSbtBW8wrNbIfwAwDIAHwCwAV9vnqqHst9sBoyhLwLwkDAYQADBBNQGopXIdgKNIj+Z2ACkATyqi/Dvz3GYYxAEAkzOJ2Kf0hUwi9qY3GFbbxb8nSZO9wfApmURsvfVuGs6+/BefJ14P4AcAJgI4F4Bqt6t/AgCfAHgLwGvpbMiR/QAlCZiXBLVNFAHwQ9JOKoSHfMYAYAJ2Pu/oiTdPDniZAx4iBTWn1tQ4ZBtG67JNpg9ljb5yfg/72Rlj548/bxPmvb8RM5/9FLv39OqMPxLAKeTTOMIz9MVf3a/gcuEEs13tk7oLRnJau08B85JwBYDnANjvPcNopGIXWxKxg95g+D0SaoN0bHVhhfjM4IjaQXj61TWY9dKqkvK3ZNtwz8wmNE85Gzc3nma6f+VQVMC8JExRCyydzi41BFkGYAWANIBdJI9a+44GsMVctxkGsTb/pZAY53y4Ag8vWtz5/cRjjp70uUtFq0X+qAWz567psocMHoiG0+txbH0NuAFcp2BXrtmO/Qd69nU9+vxn8NTV4qqvOac/r6CAeUm4mtS82ip7G4BfqOGxIsrbrXGRUSl6ojwzOqvr+9zrv73g3MjdRZ9RP3Ro9/Pa24120Rby4h12xGD86PtnofHSUagZ0rOO2rm7ozPfnPnrkMt1/xlnPrsS488bgfpjhljutx66AuYlYSSAFyjxygCCiihvts49Bo2RYeuAAVyfeWoHdb8i7R3Gd97SbToz0FmNpLJn956Oi2+fcdHy22cUvTcE4Im83bprH8Z+9+1YOhu61yR3y6JQDfww6V3O0wTgMkWU2yzyyxVE/IEeL0Y0lezXy2h1m5IOEfVo398t2mE1PWsdK8RnIo+ks6HlfWVKZ0NxnyfeSEZe8tzoHR5/ILM1ZPtU1F4C5iXhDADXapLUuOk6Jt7+47ROn21t3T9pITF6g+H71MhR/d7a1r6u7oKRzurFqYwDAH5dRv7HKAEfx3G4FMA7JvhWFno18BSq02q2Isr/stAn1+I0geqJUrug/455C+7PJGIP9/GYszXfCw45uYzl6WyonD6c9wGopd1QTdqFThXwdZT9tEW+OB5aoL+8dqrlPhgctgZIc0kXbzBcA+ByTVKTgf+2nXxSTuZ0NtTm88RXAThPkzzGeLfKp4eAeUk4E8CJmqTViiivtd4te7C7BrWhTXmxNxgen0nEFhe4fhtZnQQyf/hVC30zk1QF96ylBPz/BvpTMXQNPIGyZQt9sQQ7RerQTp+ENxi+KZOIvZtPGNH4Y47juBvIaqQ8r2cSsY32uGg4rRXcs42y6wzypV/QAj6HsrvaPLwkjCYzckQApwGoBbATQDOApQAW5JD781Jxie0rPewSqUMFWojNZOXRLWpbzhsMb1IjLjLR/xwyfTJPC4B7bPTVaCrpkN1B2Y4UMN3DuIGXBDVPDMDd1LgwyMRv9XMWgCkcuNW8JNyqiHKhkMww7BApLVB6GMllLMkB07hDPbK3AxhJPjTrAEzKJGJpG3w0i0oK2sGU7YgVTbSA6TliLaTd860Sn6fW0ot4SbhFEeUX++uc1SJ1WQ3aX+SWREwV7zRvMPxHsiPHODWCJiFmfkeO2ZlEbK/dzhpMbQX3DKPsSsJww6EF7KHsuzTiVUvgOWQCfL40PgHA10loXad55jO8JKxXRPnvpThhpVCrTKS9yCRivf7/mURM/Z1K+q0OE+j3vBR8lE2H1LZAC/goyr6BrPOdCWCGIsp0SfwZgCQvCY+Q0voikq6GG09eKI07d6m4pFOcbhFpxB+YAOB60qF3Iimtt5AhlLkAXoumkvnwqUMntGI4n5MruOd0ynbEumhawDU6eaYpojy72EMUUd7KS8JkACs17aiGGTWRg+cv+7Jx3mowuiaN+ANesvJqks5l9dpV5PPTiD9wXTSV/ISUwpWU5gx7+Wo5mX2e+LEAzqSSHXGiBS3gHNXAf1tPvIVq07f2L8RT++Z02U0HVuD8gZUL2KpwN+IPqOHRX3VKWT3Udv7iiD9wCamZmYDdR4PPEx+ZzoY2lZj/GzpLahUT/CobWsC7yI6EnTxUe/+VX1nWUHLoq4r1KXQL+J8H15R0n53t0ntHXab+26/piPdjAG+QPaMGkc3dJpFF7WpTY75TeiIZFREBcGdfmbzD46pww1Rycy6HRea5Vjq0gFu1Aj6Z0xtVKMwI7ljUcjVozx1qKm/PdXfUObXziOO4qQAEKjkcTSUf08n+UMQfuJbsE3W8RS4yzOE2nyf+bjobertYJo7r3ELoS1TynMzW0AFz3SsNOixo0Rr7Ub6P7bm9XeOFO3K7OlThOlW8BHpd5zMFxNtJNJWcS8bEGe5mIIB5Pk98us8T/z/6os8TH+HzxF8AcB91KUPNULMVugb+SI2E80ZLbgs8XK//W9HalJcE7e59jhgrK0TEHxgL4FRNUhuAB/u8MYfnwHXOTDrDVAcZZrCX7IetFtJDyO/9E58n/hEZHt1H5kOMISLXojYn70pnQ44YQoJODfyB1gi3T/9ZvgbVfgo9jJeE4dSSK6fvjXUJZS+MppJ97jgS3Zg8qJbe5rnFMJGmdDb0OICfa9IGkoprMoBryFJBPfHekc6G3rDY36LQAl5EFjvnuelCaVw54e94yl7RD9+sgB5O+FsZ91bTxIfDic4FOulsaDqA7wHIlnDPFwAmprMhxy2t7SFgRZSbASzQJJ3Kgbu1jOfdQdlFty11AKMpe3UZ91ayJI1hP11RZjobeoWMLkwl7/2/SYi9g7wLr5AauSGdDb1nr9v66C3oj5NQIk+Ml4R/KKK8tNiDeEm4kQpJ1fbv68a5agr1lN1cxr0Zg31hmEQ6GyoYRZITF35LPq6j1+FmiiirtebLmqQj1bYhLwk364XTvCQM4SXhPrKLpZYnFFHeaYrXxnE0ZZdzfMbhsccqw9UU2pXyTnL2UX7O6FEAnufAPchLwgISPg4iPbhX6IyJLjH6CA6LKHnSSjSVbI/4A+Z6w2D0ga6AFVFu5SVhAjk3VjuIPUqnnUvzAdk/2g2zlHZqtowB1YNelIg/QC8vYzAsp+D5wIoo/4ec2P6Y9jS3IvyX1LqiIsotxrppGvQ4dbGD22jo9jODYTlFz0ZSRHkHgDAvCbPICe4TSdjsI0vpNpODodWa+nVFlJ0+7kuzlpxAl+cMMpRWCofD/sgMl1PS8aKKKG8iBzzPMt8lS/mQtOHzjCtjG92ylqQxGGZQMISuEv5C2RPLaNteY4I/DEZZVLWAc7ncYmpnhXqdyeu9iPgDV7MamOEEqlrAj25cmAPwOJX8QMQfmFbonog/cDlZTshg2I6Tl/lZQmRUYAC4zvmxPHXpY7JofwOZ2H4SOYokP997FdkPq6szq7+nEzIY5cJeuEO16vFk3nYpW+qArLIaB2C69iwpJmCG1VR1CJ0nmko2kx0155eQfYUq3mgq+QWphRkM2yhpGKkaiKaSGQCNEX9gPDkfOb+t7BFkvHt55yb3Ocwj64HBBMxgMBiMimEhNIPhYpiAGQwXwwTMYLgYJmAGw8UwATMYLoYJmMFwMUzADIaLYQJmMFwMEzCD4WKYgBkMF/O/AAAA//8BQzGHXqbd+gAAAABJRU5ErkJggg==

**Comment by mojocn** [comment]
如果使用的是中文, 你的配置必须使用中文字体  `wqy-microhei.ttc`.  其他的字体不支持显示中文,导致图片内容空白.  ` var fontChinese = loadFontByName("fonts/wqy-microhei.ttc")
`

**Comment by Icarus9913** [comment]
> 如果使用的是中文, 你的配置必须使用中文字体 `wqy-microhei.ttc`. 其他的字体不支持显示中文,导致图片内容空白. `var fontChinese = loadFontByName("fonts/wqy-microhei.ttc")`

有的，我有设置这个。base64Captcha.DriverString结构体里有设置Fonts为[]string{"wqy-microhei.ttc"}，然后执行ConvertFonts方法。我的电脑是中文，但是我设置的DriverString里的source是"1234567890qwertyuioplkjhgfdsazxcvbnm"

**Comment by mojocn** [comment]
看一下你的代码

**Comment by Icarus9913** [comment]
`package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/mojocn/base64Captcha"
	"image/color"
	"net/http"
)

type CaptchaResult struct {
	Id           string `json:"id"`
	Base64Blob   string `json:"base_64_blob"`
	VertifyValue string `json:"code"`
}

var store = base64Captcha.DefaultMemStore
func GenerateCaptcha(ctx *gin.Context) {
	var driver base64Captcha.Driver
	var driverString base64Captcha.DriverString
	captchaConfig := base64Captcha.DriverString{
		Length: 4,
		Source: "1234567890qwertyuioplkjhgfdsazxcvbnm",
		Width: 240,
		Height: 60,
		NoiseCount: 0,
		ShowLineOptions:base64Captcha.OptionShowHollowLine,
		BgColor: &color.RGBA{
			R: 0,
			G: 0,
			B: 0,
			A: 0,
		},
		Fonts: []string{"wqy-microhei.ttc"},
	}
	driverString=captchaConfig
	driver=driverString.ConvertFonts()

	captcha := base64Captcha.NewCaptcha(driver,store)	//生成验证码，同时保存至store
	id, b64s, err := captcha.Generate()		//生成base64图像验证id
	if err != nil {
		panic(err)
	}
	captchaResult := CaptchaResult{
		Id:         id,
		Base64Blob: b64s,
	}
	fmt.Println("base64内容：",captchaResult.Base64Blob)
	ctx.HTML(http.StatusOK,"index.html",gin.H{
		"captcha_result": captchaResult,
	})
}`

**Comment by Icarus9913** [comment]
`package main

import (
    "fmt"
    "github.com/gin-gonic/gin"
    "github.com/mojocn/base64Captcha"
    "image/color"
    "net/http"
)

type CaptchaResult struct {
    Id           string `json:"id"`
    Base64Blob   string `json:"base_64_blob"`
    VertifyValue string `json:"code"`
}

var store = base64Captcha.DefaultMemStore

//生成图形化验证码
func GenerateCaptcha(ctx *gin.Context) {
    var driver base64Captcha.Driver
    var driverString base64Captcha.DriverString
    captchaConfig := base64Captcha.DriverString{
        Length: 4,
        Source: "1234567890qwertyuioplkjhgfdsazxcvbnm",
        Width: 240,
        Height: 60,
        NoiseCount: 0,
        ShowLineOptions:base64Captcha.OptionShowHollowLine,
        BgColor: &color.RGBA{
            R: 0,
            G: 0,
            B: 0,
            A: 0,
        },
        Fonts: []string{"wqy-microhei.ttc"},
    }
    driverString=captchaConfig
    driver=driverString.ConvertFonts()

    captcha := base64Captcha.NewCaptcha(driver,store)   //生成验证码，同时保存至store
    id, b64s, err := captcha.Generate()     //生成base64图像验证id
    if err != nil {
        panic(err)
    }
    captchaResult := CaptchaResult{
        Id:         id,
        Base64Blob: b64s,
    }
    fmt.Println("base64内容：",captchaResult.Base64Blob)
    ctx.HTML(http.StatusOK,"index.html",gin.H{
        "captcha_result": captchaResult,
    })
}


func VertifyCaptcha(id string, value string) bool {
    if id=="" || value==""{
        return false
    }
    return store.Verify(id,value,true)
}
`

**Comment by Icarus9913** [comment]
老哥，请问问题出在哪里了？

**Comment by mojocn** [comment]
Fonts: []string{"wqy-microhei.ttc"}, 改成尝试一下
  Fonts: []string{"fonts/wqy-microhei.ttc"},
