### ISSUE TITLE
mac os 无法安装的问题

### ISSUE THREAD

**Issue by Aimoy** [mojocn/base64Captcha#78]
go mod 安装包失败
提示: `../../pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/fonts.go:26:20: undefined: Asset`

![image](https://user-images.githubusercontent.com/38563666/94219097-927a2d80-ff18-11ea-85d5-1584a2754056.png)

**Comment by xxlest** [comment]
> go mod 安装包失败 提示: `../../pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/fonts.go:26:20: undefined: Asset`
> 
> ![image](https://user-images.githubusercontent.com/38563666/94219097-927a2d80-ff18-11ea-85d5-1584a2754056.png)

same with me ,did you fix it ?
