### ISSUE TITLE
v1.3.1设置高度后，报错

### ISSUE THREAD

**Issue by tuoling805** [mojocn/base64Captcha#80]
var store = base64Captcha.DefaultMemStore
	driver := base64Captcha.DefaultDriverDigit
	driver.Width = 67
	driver.Height = 26
	driver.Length = 4
	char := base64Captcha.NewCaptcha(driver, store)
	id, b64s, err := char.Generate()

Handler crashed with error invalid argument to Intn
c:/go/src/runtime/panic.go:969
c:/go/src/math/rand/rand.go:169
c:/go/src/math/rand/rand.go:337
E:/code/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/driver_digit.go:67
E:/code/go/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/captcha.go:35
E:/code/go/src/hongze/hongze_api/controllers/user_pc.go:25
c:/go/src/reflect/value.go:460
c:/go/src/reflect/value.go:321
E:/code/go/pkg/mod/github.com/astaxie/beego@v1.12.2/router.go:891
c:/go/src/net/http/server.go:2807
c:/go/src/net/http/server.go:1895
c:/go/src/runtime/asm_amd64.s:1373+

**Comment by mojocn** [comment]
go get -u github.com/mojocn/base64Captcha@v1.3.2 

driver.Font == nil 则加载默认字体
