### ISSUE TITLE
写了一个 test 然后报错了

### ISSUE THREAD

**Issue by ItsWewin** [mojocn/base64Captcha#82]
使用你的库之前，我先写了一个 Test，运行后报错了，也不知道什么原因

`func TestHandlerCaptchaGenerate(t *testing.T) {
	s := base64Captcha.DefaultMemStore

	driver := &base64Captcha.DriverString{
		Height:          80,
		Width:           240,
		NoiseCount:      10,
		ShowLineOptions: 10,
		Length:          10,
		Source:          "",
		BgColor:         nil,
		Fonts:           nil,
	}

	c := base64Captcha.NewCaptcha(driver, s)

	id, _, err := c.Generate()
	if err != nil {
		t.Fatalf("some error: %s", err)
	}

	t.Logf("id: %s", id)
}`

报错如下

`panic: invalid argument to Intn [recovered]
	panic: invalid argument to Intn

goroutine 23 [running]:
testing.tRunner.func1.1(0x12eb5c0, 0x13c8ea0)
	/usr/local/go1.14.6/go/src/testing/testing.go:988 +0x30d
testing.tRunner.func1(0xc0000f25a0)
	/usr/local/go1.14.6/go/src/testing/testing.go:991 +0x3f9
panic(0x12eb5c0, 0x13c8ea0)
	/usr/local/go1.14.6/go/src/runtime/panic.go:969 +0x166
math/rand.(*Rand).Intn(0xc00007e1e0, 0x0, 0x13cf7c0)
	/usr/local/go1.14.6/go/src/math/rand/rand.go:169 +0x9c
math/rand.Intn(...)
	/usr/local/go1.14.6/go/src/math/rand/rand.go:337
github.com/mojocn/base64Captcha.randFontFrom(...)
	/Users/klook/klook-workspace/src/klook-libs/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/fonts.go:52
github.com/mojocn/base64Captcha.(*ItemChar).drawNoise(0xc00007f230, 0xc000269aa0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x14)
	/Users/klook/klook-workspace/src/klook-libs/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/item_char.go:195 +0x301
github.com/mojocn/base64Captcha.(*DriverString).DrawCaptcha(0xc0000b41c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/klook/klook-workspace/src/klook-libs/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/driver_string.go:101 +0x1c8
github.com/mojocn/base64Captcha.(*Captcha).Generate(0xc00013bf50, 0xc0000b41c0, 0xc000568708, 0xa0026189, 0xcf9a0026189, 0x100000001, 0xc000568748)
	/Users/klook/klook-workspace/src/klook-libs/pkg/mod/github.com/mojocn/base64!captcha@v1.3.1/captcha.go:35 +0x8f
amusingx.fit/amusingx/services/amusinguserserv/api/captcha.TestHandlerCaptchaGenerate(0xc0000f25a0)
	/Users/klook/workspace/amusingx-project/amusing-x/services/amusinguserserv/api/captcha/captcha_test.go:26 +0xfb
testing.tRunner(0xc0000f25a0, 0x1377338)
	/usr/local/go1.14.6/go/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/usr/local/go1.14.6/go/src/testing/testing.go:1090 +0x372
`

**Comment by mojocn** [comment]
`	Source:          "axclajsdlfkjalskjdglasdg",`  source这个配置不能为空字符串.

如果 Fonts == nil, 我现在加了一个加载全部字体


```go

func TestHandlerCaptchaGenerate(t *testing.T) {
	s := DefaultMemStore

	driver := &DriverString{
		Height:          80,
		Width:           240,
		NoiseCount:      10,
		ShowLineOptions: 10,
		Length:          10,
		Source:          "MakeCodeDoLove",
		BgColor:         nil,
		Fonts:           nil,
	}

	c := NewCaptcha(driver, s)

	id, _, err := c.Generate()
	if err != nil {
		t.Fatalf("some error: %s", err)
	}

	t.Logf("id: %s", id)
}

```

**Comment by mojocn** [comment]
go get -u github.com/mojocn/base64Captcha@v1.3.2 

driver.Font == nil 则加载默认字体
