### ISSUE TITLE
goland 下载报证书问题

### ISSUE THREAD

**Issue by zh851122** [mojocn/base64Captcha#85]
GOPROXY=https://goproxy.cn,direct
go version go1.16 windows/amd64

go: github.com/mojocn/base64Captcha@v1.3.4: Get "https://proxy.golang.cn/github.com/mojocn/base64%21captcha/@v/v1.3.4.mod": x509: certificate signed by unknown authority

**Comment by mojocn** [comment]
你这个 应该不是我这个仓库的原因啊,  有可能是 proxy.golang.cn的原因 你尝试使用  GOPROXY=https://goproxy.io

**Comment by mojocn** [comment]
我的环境是可以的啊

```
➜  sshark git:(beta_jms) ✗ go get -u github.com/mojocn/base64Captcha
go: downloading github.com/mojocn/base64Captcha v1.3.4
go: downloading golang.org/x/image v0.0.0-20210504121937-7319ad40d33e
go get: upgraded github.com/mojocn/base64Captcha v1.3.3 => v1.3.4
go get: upgraded golang.org/x/image v0.0.0-20210220032944-ac19c3e999fb => v0.0.0-20210504121937-7319ad40d33e
➜  sshark git:(beta_jms) ✗ echo $GOPROXY
https://goproxy.cn,direct
➜  sshark git:(beta_jms) ✗ 
```

**Comment by zh851122** [comment]
部分用户报证书问题，源都是https://goproxy.cn，部分用户正常

**Comment by mojocn** [comment]
> 部分用户报证书问题，源都是[https://goproxy.cn，部分用户正常](https://goproxy.cn%EF%BC%8C%E9%83%A8%E5%88%86%E7%94%A8%E6%88%B7%E6%AD%A3%E5%B8%B8)

你换成 https://goproxy.io 尝试一下?
