### ISSUE TITLE
front.go 中的Asset是不是还没有实现？

### ISSUE THREAD

**Issue by liuyongchen** [mojocn/base64Captcha#88]
![image](https://user-images.githubusercontent.com/33820757/124871804-13fa0280-dff7-11eb-9e4b-b7cb0dd2c826.png)

**Comment by mojocn** [comment]
非也非也, 是字体 转换成 go文件之后, 文件size太大了, 不被goland识别.

**Comment by Jaylynn123** [comment]
Jaime Conley string
