### ISSUE TITLE
v1.3.4 报错error github.com/mojocn/base64!captcha@v1.3.4/captcha.go:34

### ISSUE THREAD

**Issue by 54huige** [mojocn/base64Captcha#95]
有人遇到过以下错误吗  运行的官方demo
1. runtime error: invalid memory address or nil pointer dereference
   1).  github.com/gogf/gf/net/ghttp.niceCallFunc.func1
        G:/xxxx/golang/pkg/mod/github.com/gogf/gf@v1.16.1/net/ghttp/ghttp_func.go:38
   2).  github.com/mojocn/base64Captcha.(*Captcha).Generate
        G:/xxxx/golang/pkg/mod/github.com/mojocn/base64!captcha@v1.3.4/captcha.go:34
   3).  b2b2c/app/domain.(*adminDomain).GetGenerateCaptcha
@mxey @Luckyboys @amzyang @slayercat @JJJJJJJerk

**Comment by mojocn** [comment]
post json 参数里面有空值导致的

**Comment by mojocn** [comment]
demo 你要结合前端 html代码一起使用
