### ISSUE TITLE
如何设置字体大小

### ISSUE THREAD

**Issue by abnerxc** [mojocn/base64Captcha#97]
rt

**Comment by medasz** [comment]
rt是什么意思？

**Comment by abnerxc** [comment]
如标题描述，如何能设置字体大小

**Comment by InsipidJC** [comment]
官方目前好像没有提供修改字体大小的方法。

需要手动修改源码里的参数（item_char.go 220行 的第二个 "7"）。数字越大，字体越大。
`fontSize := item.height * (rand.Intn(7) + 7) / 16`
